apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: main-ctr
        image: santhoshtns/getting-started-k8s:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
