apiVersion: v1
kind: Pod
metadata:
  name: busybox-livenessprobe
  labels:
    name: busybox-livenessprobe
spec:
  containers:
  - name: busybox-livenessprobe
    image: k8s.gcr.io/busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 60
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
