apiVersion: v1
kind: Pod
metadata:
  name: myapp-livenessprobe
  labels:
    app: web
    use: livenessprobe
spec:
  containers:
  - name: my-nginx-ctr
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2 # Default is 1
      periodSeconds: 5 # Default is 10
      failureThreshold: 1 # Default is 3
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshold: 1
